[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = '0.8.17'
optimizer = true
optimizer_runs = 5000
# via_ir = false

[rpc_endpoints]
goerli = "${RPC_URL}"
mainnet = "${RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config